server:
  port: 8090

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/woj_csb_db
      username: root
      password: 123456
  redis:
    database: 2
    host: localhost
    port: 6379
    timeout: 5000